//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TStudent.cpp
//  @ Date : 2018-03-18
//  @ Author : 
//
// // cwiczenia 3 zadanie 1


#include "TStudent.h"

TStudent::TStudent() {

}

TStudent::~TStudent() {

}

