//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TStudent.h
//  @ Date : 2018-03-18
//  @ Author : 
//
// cwiczenia 3 zadanie 1


#if !defined(_TSTUDENT_H)
#define _TSTUDENT_H


class TStudent {
public:
	TStudent();
	~TStudent();
};

#endif  //_TSTUDENT_H
