//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TUniversity.cpp
//  @ Date : 2018-03-18
//  @ Author : 
//
// // cwiczenia 3 zadanie 1


#include "TUniversity.h"

void TUniversity::attach() {

}

void TUniversity::detach() {

}

