//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TUniversity.h
//  @ Date : 2018-03-18
//  @ Author :
//
// cwiczenia 3 zadanie 1


#if !defined(_TUNIVERSITY_H)
#define _TUNIVERSITY_H
#include <vector>

using namespace std;

class TUniversity {
public:
	void attach();
	void detach();
private:
	vector<TStudent*> students;
	vector<TStudent*>::iterator it;
};

#endif  //_TUNIVERSITY_H
