//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Bernoulli.cpp
//  @ Date : 2018-03-24
//  @ Author : 
//
//


#include "Bernoulli.h"

void Bernoulli::setPQ() {
    std::cout << "Podaj prawdopodobienstwo sukcesu (licznik i mianownik oddzielone spacja \n";
    int x, y;
    std::cin >> x >> y;
    this->p = ((x * 1.00000) / (y*1.00000)) * 1.00000;
    this->q = 1.00000 - p;
}

double Bernoulli::llicz()
{
    wynik = newton.licz(n,k) * potega.licz(p,k) * potega.licz(q,(n-k));
    std::cout << wynik << " \n";
}

Bernoulli::Bernoulli() {
    std::cout << "Podaj ilosc prob: \n";
    std::cin >> n;
    std::cout << "Podaj ilosc sukcesow: \n";
    std::cin >> k;
    std::cout << "Podaj ilosc mozliwosci: \n";
    setPQ();

}

