//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Newton.h
//  @ Date : 2018-03-24
//  @ Author : 
//
//


#if !defined(_NEWTON_H)
#define _NEWTON_H

#include "Silnia.h"

class Newton {
public:
	int licz(int n, int k);
private:
	Silnia silnia;
};

#endif  //_NEWTON_H
