//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Potega.cpp
//  @ Date : 2018-03-24
//  @ Author : 
//
//


#include "Potega.h"

double Potega::licz(double x, int y) {
    if(y == 0)
        return 1;

    double wynik = 1;

    for(int i=0; i<y; i++ )
        wynik *= x;
    return wynik;
}

