//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Potega.h
//  @ Date : 2018-03-24
//  @ Author : 
//
//


#if !defined(_POTEGA_H)
#define _POTEGA_H


class Potega {
public:
	double licz(double x, int y);
};

#endif  //_POTEGA_H
