//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Silnia.h
//  @ Date : 2018-03-24
//  @ Author : 
//
//


#if !defined(_SILNIA_H)
#define _SILNIA_H


class Silnia {
public:
	int licz(int x);
};

#endif  //_SILNIA_H
