//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Silnia.cpp
//  @ Date : 2018-03-24
//  @ Author : 
//
//


#include "Silnia.h"

int Silnia::licz(int x) {
    if(x == 0)
        return 1;

    int wynik = 1;

    for(int i = x; i > 0; i--)
        wynik *= i;

    return wynik;
}

