//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TStudent.h
//  @ Date : 2018-03-18
//  @ Author :
//
// cw 3 zad 2


#if !defined(_TSTUDENT_H)
#define _TSTUDENT_H

using namespace std;

class TStudent {
public:
	TStudent();
	~TStudent();
	void setName(string name);
	void setAge(int age);
	string getName();
	int getAge();
private:
	string studentName;
	int studentAge;
};

#endif  //_TSTUDENT_H
