//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TUniversity.cpp
//  @ Date : 2018-03-18
//  @ Author :
//
// cw 3 zad 2


#include "TUniversity.h"


void TUniversity::attach(TStudent* st) {
    this->students.push_back(st);
}

void TUniversity::detach() {
    this->students.pop_back();
}

void TUniversity::printData(int i) {
    if(i >= 0 && i < this->students.size())
        cout << this->students[i]->getName() << " " << this->students[i]->getAge() << endl;
    else
        cout << "Nie ma studenta pod " << i << " indeksem \n";
}

void TUniversity::setData(int i, string name, int age) {
    this->students[i]->setName(name);
    this->students[i]->setAge(age);
}

